// <auto-generated />
using System;
using Chat.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Chat.Migrations
{
    [DbContext(typeof(ChatContext))]
    partial class ChatContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854");

            modelBuilder.Entity("Models.ChatSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<int>("TrainingId");

                    b.Property<int>("Type");

                    b.HasKey("Id");

                    b.ToTable("ChatSessions");
                });

            modelBuilder.Entity("Models.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("ChatSessionId");

                    b.Property<string>("Sender");

                    b.Property<string>("SessionName");

                    b.Property<string>("Text");

                    b.Property<DateTime>("TimeStamp");

                    b.HasKey("Id");

                    b.HasIndex("ChatSessionId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("Models.Scenario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Scenarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "SQL injection is a code injection technique that might destroy your database.SQL injection is one of the most common web hacking techniques.SQL injection is the placement of malicious code in SQL statements, via web page input.",
                            Name = "SQLInjection"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Slowloris is a type of denial of service attack tool invented by Robert 'RSnake' Hansen which allows a single machine to take down another machine's web server with minimal bandwidth and side effects on unrelated services and ports.",
                            Name = "Apache Shutdown"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Any malicious computer program which misleads users of its true intent. The term is derived from the Ancient Greek story of the deceptive wooden horse that led to the fall of the city of.",
                            Name = "Trojan"
                        });
                });

            modelBuilder.Entity("Models.SessionUser", b =>
                {
                    b.Property<int>("SessionId");

                    b.Property<int>("UserId");

                    b.HasKey("SessionId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("SessionsUsers");
                });

            modelBuilder.Entity("Models.Training", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<int?>("ScenarioId");

                    b.Property<int>("State");

                    b.HasKey("Id");

                    b.HasIndex("ScenarioId");

                    b.ToTable("Trainings");
                });

            modelBuilder.Entity("Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<string>("UserName");

                    b.Property<int>("UserType");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "sdfdsf@sdfdsf.com",
                            FirstName = "Bot",
                            LastName = "Marley",
                            UserName = "Marley",
                            UserType = 1
                        },
                        new
                        {
                            Id = 2,
                            Email = "dfdsfsfsdfdsf@sdfdsf.com",
                            FirstName = "Ksenia",
                            LastName = "Sadrina",
                            UserName = "Makaka",
                            UserType = 0
                        });
                });

            modelBuilder.Entity("Models.Message", b =>
                {
                    b.HasOne("Models.ChatSession")
                        .WithMany("Messages")
                        .HasForeignKey("ChatSessionId");
                });

            modelBuilder.Entity("Models.SessionUser", b =>
                {
                    b.HasOne("Models.ChatSession", "Session")
                        .WithMany("Users")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Models.User", "User")
                        .WithMany("Sessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Models.Training", b =>
                {
                    b.HasOne("Models.Scenario", "Scenario")
                        .WithMany()
                        .HasForeignKey("ScenarioId");
                });
#pragma warning restore 612, 618
        }
    }
}
